FROM mcr.microsoft.com/playwright:v1.63.0-noble

WORKDIR /tests
COPY package.json package-lock.json ./
COPY packages/core/package.json packages/core/package.json
COPY mds-patient/package.json mds-patient/package.json
COPY mds-staff/package.json mds-staff/package.json
RUN npm ci --ignore-scripts
COPY playwright.config.js ./
COPY e2e ./e2e
ENV CI=1 E2E_CORE=1
CMD ["npm", "run", "test:gui", "--", "--project=core"]
