scalar Date


enum USER_SEX {
    Male
    Female
}

enum USER_CIVILSTATUS {
    Single
    Married
    Widowed
    Divorced
    Separated
}

enum USER_BRANCH {
  Manila
  QuezonCity
  Both
}

type userProfile{
  id: ID!
  first_name: String!
  middle_name: String!
  last_name: String!
  suffix: String
  date_of_birth: Date!
  sex: USER_SEX!
  civil_status: USER_CIVILSTATUS!
  nationality: String!
  religion: String!
  contactNumber: String!
  present_address: String!
  province_address: String!
  status: UpdateStatus!
  email: String
  branch: USER_BRANCH
  identifier: ID
  updated_at: Date
  created_at: Date
}

input userProfileInput{
  first_name: String!
  middle_name: String!
  last_name: String!
  suffix: String
  date_of_birth: Date!
  sex: USER_SEX!
  civil_status: USER_CIVILSTATUS!
  nationality: String!
  religion: String!
  contactNumber: String!
  present_address: String!
  province_address: String!
}

input userProfileUpdateInput{
  first_name: String
  middle_name: String
  last_name: String
  suffix: String
  date_of_birth: Date
  sex: USER_SEX!
  civil_status: USER_CIVILSTATUS
  nationality: String
  religion: String
  contactNumber: String
  present_address: String
  province_address: String
}



type BranchIdentifier{
  branch: USER_BRANCH!
  identifier: ID!
}

input BranchIdentifierInput{
  branch: USER_BRANCH
  identifier: ID!
}

input BranchIdentifierUpdateInput{
  branch: USER_BRANCH
  identifier: ID
}

enum UpdateStatus{
    InProgress
    Pending
    Revision
    RevisionSubmitted
    Expired
    Cancelled
    Approved
}

enum CredentialStatus{
  Unverified
  Active
  Locked
  Disabled
}

# Queries
type Query {
  # Student queries
  getCredentialStatus: String # get is unverified or not
  getUserCredentialStatus(userId: ID!): String

  getPersonalRecord: userProfile # get the main record of the logged in user 
  getUserPersonalRecord(userId: ID!): userProfile

  getPersonalRecordLogStatus: String # get the update status of the logged in user
  getUserPersonalRecordLogStatus(userId: ID!): String

  getPersonalRecordLog: userProfile
  getUserPersonalRecordLog(userId: ID!, from: Date, offset: Int, limit: Int): [userProfile!]

  getBranchIdentifier: BranchIdentifier
  getUserBranchIdentifier(userId: ID!): BranchIdentifier

}

# Mutations
type Mutation {
  createPersonalRecordLog(input: userProfileInput!): userProfile
  # createPersonalRecordLog for patient pr creation, while updatePersonalRecordLog for patient pr update
  # while updatePatientPersonalRecordLog for patient pr update
  updatePatientPersonalRecordLog(input: userProfileUpdateInput!): userProfile

  updatePersonalRecordLog(userId: ID!, input: userProfileUpdateInput!): userProfile

  createBranchIdentifier(input: BranchIdentifierInput!): BranchIdentifier 
  updateUserBranchIdentifier(userId: ID!, input: BranchIdentifierUpdateInput!): BranchIdentifier

  setPersonalRecordLog(userId: ID!, status: UpdateStatus!): UpdateStatus
  cancelPersonalRecordLog: String

  reloadCredentialStatus: String
  reloadUserCredentialStatus(userId: ID!): String
  
  staffSetCredentialStatus(userId: ID!, status: CredentialStatus!): CredentialStatus


}
