

enum USER_SEX {
    Male
    Female
}

enum USER_CIVILSTATUS {
    Single
    Married
    Widowed
    Divorced
    Separated
}


type userProfile{
  id: ID!
  first_name: String!
  middle_name: String!
  last_name: String!
  suffix: String!
  date_of_birth: Date!
  sex: USER_SEX!
  status: USER_CIVILSTATUS!
  nationality: String!
  religion: String!
  contactNumber: String!
  present_address: String!
  province_address: String!
  email: String
  entityId: ID
  updated_at: Date
  created_at: Date
}

input userProfileInput{
  first_name: String!
  middle_name: String!
  last_name: String!
  suffix: String!
  date_of_birth: Date!
  sex: USER_SEX!
  status: USER_CIVILSTATUS!
  nationality: String!
  religion: String!
  contactNumber: String!
  present_address: String!
  province_address: String!
  email: String!
  entityId: ID!
}

input userProfileUpdateInput{
  first_name: String
  middle_name: String
  last_name: String
  suffix: String
  date_of_birth: Date
  sex: USER_SEX
  status: USER_CIVILSTATUS
  nationality: String
  religion: String
  contactNumber: String
  present_address: String
  province_address: String
}

type userAnchorData{
  id: ID!
  email: String!
  entityId: ID!
}

input userAnchorDataInput{
  email: String
  entityId: ID
}


# Queries
type Query {
  # Student queries
  getCredentialStatus: String # get is unverified or not
  getUserCredentialStatus(userId: ID!): String

  getPersonalRecord: userProfile # get the main record of the logged in user 
  getUserPersonalRecord(userId: ID!): userProfile

  getPersonalRecordLogStatus: String # get the update status of the logged in user
  getUserPersonalRecordLogStatus(userId: ID!): String

  getPersonalRecordLog: userProfile
  getUserPersonalRecordLog(userId: ID!, from: Date, offset: Int, limit: Int): [userProfile!]

  getAnchorData: userAnchorData
  getUserAnchorData(userId: ID!): userAnchorData
}

# Mutations
type Mutation {
  # Student mutations
  updatePersonalRecord(input: userProfileUpdateInput!): userProfile
  createPersonalRecord(input: userProfileInput!): userProfile
  
  staffSetPersonalRecord(userId: ID!, status: UpdateStatus!): UpdateStatus
  cancelUpdatePersonalRecord: String

  reloadCredentialStatus: String
  staffSetCredentialStatus(userId: ID!, status: CredentialStatus!): CredentialStatus

  updateUserAnchorData(data: userAnchorDataInput!): userAnchorData

}
