CREATE TYPE "userIdentity" AS ENUM (
  'Student',
  'Employee',
  'Superior',
  'Medical'
);

CREATE TYPE "procedureDomain" AS ENUM (
  'VisualAcuity',
  'Medication',
  'Hospitalization',
  'Operation',
  'Immunization',
  'DentalProcedure'
);

CREATE TYPE "AuditActor" AS ENUM (
  'Patient',
  'Staff',
  'System'
);

CREATE TYPE "patientIdentity" AS ENUM (
  'Student',
  'Employee'
);

CREATE TYPE "CredentialStatus" AS ENUM (
  'unverified',
  'active',
  'locked',
  'disabled'
);

CREATE TYPE "LocationDesignation" AS ENUM (
  'Arlegui',
  'Casal',
  'QuezonCity'
);

CREATE TYPE "UserDesignation" AS ENUM (
  'Manila',
  'QuezonCity',
  'Both'
);

CREATE TYPE "employeeRole" AS ENUM (
  'Employee',
  'Faculty',
  'Staff',
  'AcademicHead',
  'Executive',
  'Other'
);

CREATE TYPE "studentYear" AS ENUM (
  'Grade11',
  'Grade12',
  'Freshman',
  'Sophomore',
  'Junior',
  'Senior',
  'Masteral',
  'Doctorate'
);

CREATE TYPE "UpdateStatus" AS ENUM (
  'InProgress',
  'Pending',
  'Revision',
  'RevisionSubmitted',
  'Cancelled',
  'Expired',
  'Approved',
  'Rejected'
);

CREATE TYPE "UpdateScope" AS ENUM (
  'Medical',
  'Dental',
  'Both'
);

CREATE TYPE "usersSex" AS ENUM (
  'Male',
  'Female'
);

CREATE TYPE "civil_status" AS ENUM (
  'Single',
  'Married',
  'Widowed',
  'Separated'
);

CREATE TYPE "dental_cleaning_range" AS ENUM (
  '0-6',
  '7-12',
  '12-24',
  '>24'
);

CREATE TYPE "boost_status" AS ENUM (
  'given',
  'pending',
  'missed',
  'scheduled'
);

CREATE TYPE "allergy_status" AS ENUM (
  'Active',
  'Resolved',
  'Suspected'
);

CREATE TYPE "allergy_type" AS ENUM (
  'food',
  'drug',
  'environment',
  'insect',
  'chemical',
  'other'
);

CREATE TYPE "severity" AS ENUM (
  'none',
  'very_mild',
  'mild',
  'moderate',
  'moderately_severe',
  'severe',
  'anaphylactic',
  'critical',
  'unknown'
);

CREATE TYPE "arch_designation" AS ENUM (
  'None',
  'Upper',
  'Lower',
  'Both'
);

CREATE TYPE "consultatationMode" AS ENUM (
  'Onsite',
  'Virtual'
);

CREATE TYPE "userType" AS ENUM (
  'Patient',
  'Medical'
);

CREATE TYPE "consultationType" AS ENUM (
  'Medical',
  'Dental'
);

CREATE TYPE "consultationStatus" AS ENUM (
  'open',
  'completed',
  'cancelled',
  'expired'
);

CREATE TYPE "dentalLegend" AS ENUM (
  'Present',
  'Due filling/decayed',
  'Due extraction',
  'Root fragment',
  'Missing',
  'Filled',
  'Gold crown',
  'Jacket crown',
  'Abutment',
  'Pontic',
  'Fixed Bridge',
  'Removeable denture',
  'Full denture'
);

CREATE TYPE "promptType" AS ENUM (
  'text',
  'file',
  'system'
);

CREATE TYPE "appliance_status" AS ENUM (
  'Active',
  'Lost',
  'Replaced',
  'Discontinued',
  'Pending',
  'Returned',
  'Failed'
);

CREATE TYPE "scheduleSession" AS ENUM (
  'Morning',
  'Afternoon'
);

CREATE TYPE "clinicalOutcome" AS ENUM (
  'Resolved',
  'Referred',
  'Monitoring'
);

CREATE TYPE "schedulingStatus" AS ENUM (
  'Pending',
  'Scheduled',
  'Rejected',
  'Expired',
  'InProgress',
  'Completed',
  'NoShow',
  'CancelledByPatient',
  'CancelledByMedical'
);

CREATE TYPE "emergencyStatus" AS ENUM (
  'Monitoring',
  'Administered',
  'Transfered',
  'Observation'
);

CREATE TYPE "itemCategory" AS ENUM (
  'medicine',
  'supply',
  'instrument',
  'equipment'
);

CREATE TYPE "DosageUnit" AS ENUM (
  'mg',
  'g',
  'mcg',
  'ml',
  'L',
  'IU'
);

CREATE TYPE "SupplyUnit" AS ENUM (
  'pcs',
  'box',
  'pack',
  'set',
  'kit'
);

CREATE TYPE "TransactionActionType" AS ENUM (
  'issue',
  'return',
  'adjust'
);

CREATE TYPE "complaintCategory" AS ENUM (
  'general',
  'respiratory',
  'pain',
  'gastrointestinal',
  'musculoskeletal',
  'dermatologic',
  'psychiatric'
);

CREATE TABLE "UserCredentials" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password_hash" varchar(255),
  "identity" "userIdentity",
  "email" varchar(100) UNIQUE,
  "allow_email_2fa" bool DEFAULT false,
  "data_consent" bool,
  "data_consent_version" varchar(8),
  "data_consent_agreed" timestamp,
  "credentials_status" "CredentialStatus",
  "locked_until" timestamp,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "UserLoginAttempt" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "attempted_at" timestamp DEFAULT (current_timestamp),
  "was_successful" boolean DEFAULT false
);

CREATE TABLE "UsersPersonal" (
  "id" integer PRIMARY KEY,
  "first_name" varchar(50),
  "middle_name" varchar(50),
  "last_name" varchar(50),
  "suffix" varchar(10),
  "date_of_birth" date,
  "sex" "usersSex",
  "civil_status" civil_status,
  "nationality" varchar(50),
  "religion" varchar(50),
  "contactNumber" varchar(15),
  "present_address" text,
  "province_address" text,
  "identifier" integer UNIQUE,
  "branch" "UserDesignation",
  "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "UsersPersonalLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "first_name" varchar(50),
  "middle_name" varchar(50),
  "last_name" varchar(50),
  "suffix" varchar(10),
  "date_of_birth" date,
  "sex" "usersSex",
  "civil_status" civil_status,
  "nationality" varchar(50),
  "religion" varchar(50),
  "contactNumber" varchar(15),
  "present_address" text,
  "province_address" text,
  "status" "UpdateStatus",
  "approvedBy" integer,
  "created_at" timestamp
);

CREATE TABLE "Patients" (
  "id" integer PRIMARY KEY,
  "profile" "patientIdentity",
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "PatientDocuments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientId" integer,
  "templateId" integer,
  "documentId" integer,
  "issuedBy" integer,
  "expired_at" timestamp,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "documentTemplate" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template" varchar(50) UNIQUE NOT NULL,
  "description" text,
  "revisedDate" varchar(7) NOT NULL,
  "createdBy" integer,
  "createdAt" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "documentData" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documentId" integer,
  "requirementId" integer,
  "data" text NOT NULL
);

CREATE TABLE "documentRequirements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "templateId" integer,
  "requirementtagId" integer
);

CREATE TABLE "documentRequirementsTag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vartag" varchar(30) NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "slotScheduler" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar(30),
  "location" "LocationDesignation",
  "scheduleFlags" smallint,
  "morningAllowed" smallint,
  "afternoonAllowed" smallint,
  "notes" text,
  "isActive" bool DEFAULT true,
  "containsCustomDates" bool,
  "whitelistOnly" bool DEFAULT false,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "SlotCustomDate" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slotScheduleId" integer,
  "scheduledDate" date,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "schedulerWhitelist" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slotSchedulerId" integer,
  "patientId" integer
);

CREATE TABLE "ScheduleDateEntity" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slotId" integer,
  "morningAllowed" integer,
  "afternoonAllowed" integer,
  "allowDuring" bool DEFAULT false,
  "scheduledDate" date NOT NULL
);

CREATE TABLE "MedicalItems" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_code" varchar(50) UNIQUE,
  "item_name" varchar(100),
  "category" "itemCategory",
  "subcategory" varchar(50),
  "description" text,
  "reorder_level" integer,
  "active" bool DEFAULT true,
  "created_at" timestamp DEFAULT (current_timestamp),
  "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "MedicineInventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_item_id" integer,
  "batch_number" varchar(50),
  "dosage_unit" "DosageUnit",
  "dosage_value" integer,
  "initial_quantity" integer,
  "current_quantity" integer,
  "expiry_date" date,
  "location" "LocationDesignation",
  "received_at" date,
  "received_by" integer,
  "supplier_name" varchar(100),
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "MedicineTransactionLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medicine_inventory_id" integer,
  "patient_id" integer,
  "action" "TransactionActionType",
  "quantity" integer,
  "issued_by" integer,
  "issued_at" timestamp DEFAULT (current_timestamp),
  "notes" text
);

CREATE TABLE "SupplyInventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supply_item_id" integer,
  "batch_number" varchar(50),
  "initial_quantity" integer,
  "current_quantity" integer,
  "unit" "SupplyUnit",
  "expiry_date" date,
  "location" "LocationDesignation",
  "received_at" date,
  "receivedBy" integer,
  "supplier_name" varchar(100),
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "SupplyTransactionLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supply_inventory_id" integer,
  "action" "TransactionActionType",
  "quantity" integer,
  "issued_by" integer,
  "issued_at" timestamp DEFAULT (current_timestamp),
  "notes" text
);

CREATE TABLE "ClinicRoom" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "location" "LocationDesignation",
  "capacity" smallint DEFAULT 1,
  "isAvailable" bool DEFAULT true,
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ClinicalEmergency" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientId" integer,
  "administeredBy" integer,
  "roomId" integer,
  "status" "emergencyStatus",
  "timeIn" timestamp,
  "timeOut" timestamp,
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ClinicVisitation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "procedure_id" integer,
  "purpose" text,
  "timeIn" timestamp DEFAULT (current_timestamp),
  "timeOut" timestamp
);

CREATE TABLE "profileRecord" (
  "id" integer PRIMARY KEY,
  "profile_type" "patientIdentity" NOT NULL
);

CREATE TABLE "student_profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profileId" integer UNIQUE,
  "program" varchar(50),
  "year" "studentYear"
);

CREATE TABLE "employee_profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profileId" integer UNIQUE,
  "department" varchar(50),
  "role" "employeeRole",
  "position" varchar(50)
);

CREATE TABLE "patientUpdateLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientId" integer,
  "status" "UpdateStatus",
  "scope" "UpdateScope",
  "notes" text,
  "approved_by" integer,
  "created_at" timestamp DEFAULT (current_timestamp),
  "archived_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "patientSlot" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientId" integer,
  "slotEntityId" integer,
  "status" "schedulingStatus",
  "session" "scheduleSession",
  "approvedBy" integer,
  "arrived_at" timestamp,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "patientScheduleRequirement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scheduleRequirementId" integer,
  "patientSlotId" integer,
  "filename" uuid,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "scheduleRequirement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slotId" integer,
  "label" varchar(100),
  "notes" text,
  "isDigital" bool DEFAULT true,
  "isActive" bool DEFAULT true
);

CREATE TABLE "MedicalPersonnel" (
  "id" integer PRIMARY KEY,
  "role" varchar(50),
  "title" varchar(50),
  "designation" "UserDesignation",
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "rolesMap" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personnelId" integer,
  "rolesId" integer,
  "branch" "UserDesignation",
  "assignedBy" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "RolesTable" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar(30),
  "data" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "DomainTypeCatalog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain" "procedureDomain" NOT NULL,
  "code" varchar(50) UNIQUE,
  "name" varchar(100) NOT NULL,
  "description" text,
  "isValid" bool DEFAULT false,
  "created_by" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "EmergencyNumber" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contactName" varchar,
  "relationship" varchar,
  "contactNumber" varchar(15),
  "isVerified" bool DEFAULT false,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "EmergencyContact" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstNumber" integer,
  "secondNumber" integer
);

CREATE TABLE "Immunization" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "ImmunizationRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "immunizationId" integer,
  "vaccineTypeId" integer,
  "doseNumber" smallint,
  "immunizationDate" date
);

CREATE TABLE "AllergenCatalog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" allergy_type,
  "allergen" varchar(50),
  "isValid" bool DEFAULT false,
  "created_by" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "Allergy" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "AllergyRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "allergyId" integer,
  "allergenCatalogId" integer,
  "status" allergy_status,
  "severity" severity,
  "notes" text,
  "date_identified" date
);

CREATE TABLE "MedicalHistory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "MedicalCondition" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medicalHistoryId" integer,
  "conditionId" integer,
  "relationship" varchar(30),
  "description" text,
  "diagnosedDate" date
);

CREATE TABLE "Hospitalization" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "HospitalizationRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospitalizationId" integer,
  "conditionId" integer,
  "admissionDate" date NOT NULL,
  "dischargeDate" date,
  "notes" text
);

CREATE TABLE "Operation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "OperationRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operationId" integer,
  "procedureId" integer,
  "operationDate" date NOT NULL,
  "notes" text
);

CREATE TABLE "VitalSigns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recorded_at" date,
  "height_cm" decimal(5,2),
  "weight_kg" decimal(5,2),
  "blood_pressure" varchar(10),
  "heart_rate" integer,
  "temperature" decimal(4,1),
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "Lifestyle" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "smoker" boolean NOT NULL,
  "numberOfCigarettesPerDay" smallint,
  "yearsSmoked" smallint,
  "alcoholConsumer" boolean NOT NULL,
  "frequencyOfAlcoholConsumption" varchar(30),
  "notes" text
);

CREATE TABLE "VisualAcuityRecord" (
  "id" integer PRIMARY KEY,
  "acuityId" integer,
  "recorded_at" date,
  "left_eye" varchar(10) NOT NULL,
  "right_eye" varchar(10) NOT NULL,
  "notes" text
);

CREATE TABLE "VisualAcuity" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "MedicationRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medicationId" integer,
  "medicineId" integer,
  "description" text
);

CREATE TABLE "MaintenanceMedication" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "ObGynHistory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lastMenstrualPeriod" date NOT NULL,
  "hasDysmenorrhea" boolean NOT NULL,
  "notes" text
);

CREATE TABLE "DentalHistoryRecord" (
  "id" integer PRIMARY KEY
);

CREATE TABLE "DentalHistory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seenByDentist" boolean NOT NULL,
  "lastVisitDate" date,
  "purpose" varchar(100),
  "lastDentalCleaning" dental_cleaning_range NOT NULL
);

CREATE TABLE "OralAppliance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "OralApplianceRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applianceId" integer,
  "status" appliance_status,
  "dateIssued" date,
  "tagId" integer,
  "arch" arch_designation
);

CREATE TABLE "oralApplianceCatalog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "description" text,
  "archable" boolean DEFAULT true,
  "isActive" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "DentalProcedure" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "DentalProcedureRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dentalProcedureId" integer,
  "procedureTypeId" integer,
  "procedureDate" date
);

CREATE TABLE "DentalPhotoRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "upperTeeth" uuid,
  "lowerTeeth" uuid,
  "isValid" bool DEFAULT true
);

CREATE TABLE "Consultation" (
  "id" integer UNIQUE PRIMARY KEY,
  "followUpID" integer,
  "patientId" integer,
  "mode" "consultatationMode",
  "type" "consultationType",
  "status" "consultationStatus",
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ConsultationVirtual" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "session_start" timestamp,
  "session_end" timestamp,
  "consent_logged" boolean DEFAULT false,
  "archived_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ConsultationVirtualPrompt" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationVirtualId" integer,
  "text" text,
  "filename" uuid,
  "promptType" "promptType",
  "userId" integer,
  "userType" "userType",
  "stamp" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ConsultationComplaints" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "complaintTag" integer,
  "onset_date" date,
  "severity" severity,
  "notes" text
);

CREATE TABLE "ComplaintTags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar(100),
  "category" "complaintCategory",
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ComplaintTagLinks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "complaintId" integer,
  "tagId" integer
);

CREATE TABLE "ConsultationPEFindings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "system_examined" varchar(50),
  "fileId" uuid,
  "findings" text,
  "notes" text
);

CREATE TABLE "ConsultationDiagnosis" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "diagnosis_name" varchar(100),
  "diagnosis_code" varchar(20),
  "diagnosis_type" varchar(30),
  "notes" text,
  "diagnosed_by" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ConsultationTreatment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "treatment_description" text,
  "medication_prescribed" varchar(100),
  "dosage_unit" "DosageUnit",
  "dosage_value" integer,
  "frequency" varchar(50),
  "remarks" text,
  "issued_by" integer
);

CREATE TABLE "ConsultationOutcome" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationId" integer,
  "outcome" "clinicalOutcome",
  "description" text,
  "recordedBy" integer,
  "recordedAt" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "ComplaintDiagnosisLink" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "complaintId" integer,
  "diagnosisId" integer,
  "linkedAt" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "DiagnosisTreatmentLink" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "diagnosisId" integer,
  "treatmentId" integer,
  "linkedAt" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "DiagnosisPEFindingsLink" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "findingId" integer,
  "diagnosisId" integer,
  "linkedAt" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "DentalRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "oralFindingRecord" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dentalRecordId" integer,
  "oralFindingId" integer,
  "status" bool DEFAULT false,
  "notes" text
);

CREATE TABLE "oralFindingCatalog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "description" text,
  "isActive" bool DEFAULT true,
  "created_by" integer,
  "created_at" timestamp
);

CREATE TABLE "ToothPlacement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dentalRecordId" integer,
  "toothIndex" smallint,
  "legend" "dentalLegend"
);

CREATE TABLE "UpdateChangesLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "childTable" varchar(50) NOT NULL,
  "record_id" integer NOT NULL,
  "fields" jsonb,
  "changedBy" "userType",
  "created_at" timestamp DEFAULT (current_timestamp)
);

COMMENT ON COLUMN "ConsultationPEFindings"."system_examined" IS 'e.g., respiratory, oral cavity';

ALTER TABLE "UserLoginAttempt" ADD FOREIGN KEY ("user_id") REFERENCES "UserCredentials" ("id");

ALTER TABLE "UsersPersonalLog" ADD FOREIGN KEY ("user_id") REFERENCES "UserCredentials" ("id");

ALTER TABLE "SlotCustomDate" ADD FOREIGN KEY ("slotScheduleId") REFERENCES "slotScheduler" ("id");

ALTER TABLE "ScheduleDateEntity" ADD FOREIGN KEY ("slotId") REFERENCES "slotScheduler" ("id");

ALTER TABLE "MedicineInventory" ADD FOREIGN KEY ("medical_item_id") REFERENCES "MedicalItems" ("id");

ALTER TABLE "MedicineInventory" ADD FOREIGN KEY ("received_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "MedicineTransactionLog" ADD FOREIGN KEY ("medicine_inventory_id") REFERENCES "MedicineInventory" ("id");

ALTER TABLE "MedicineTransactionLog" ADD FOREIGN KEY ("patient_id") REFERENCES "Patients" ("id");

ALTER TABLE "MedicineTransactionLog" ADD FOREIGN KEY ("issued_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "SupplyInventory" ADD FOREIGN KEY ("supply_item_id") REFERENCES "MedicalItems" ("id");

ALTER TABLE "SupplyInventory" ADD FOREIGN KEY ("receivedBy") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "SupplyTransactionLog" ADD FOREIGN KEY ("supply_inventory_id") REFERENCES "SupplyInventory" ("id");

ALTER TABLE "SupplyTransactionLog" ADD FOREIGN KEY ("issued_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "ClinicalEmergency" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "ClinicalEmergency" ADD FOREIGN KEY ("administeredBy") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "ClinicalEmergency" ADD FOREIGN KEY ("roomId") REFERENCES "ClinicRoom" ("id");

ALTER TABLE "ClinicVisitation" ADD FOREIGN KEY ("procedure_id") REFERENCES "ClinicalEmergency" ("id");

ALTER TABLE "student_profile" ADD FOREIGN KEY ("profileId") REFERENCES "profileRecord" ("id");

ALTER TABLE "employee_profile" ADD FOREIGN KEY ("profileId") REFERENCES "profileRecord" ("id");

ALTER TABLE "patientScheduleRequirement" ADD FOREIGN KEY ("scheduleRequirementId") REFERENCES "scheduleRequirement" ("id");

ALTER TABLE "patientScheduleRequirement" ADD FOREIGN KEY ("patientSlotId") REFERENCES "patientSlot" ("id");

ALTER TABLE "ImmunizationRecord" ADD FOREIGN KEY ("immunizationId") REFERENCES "Immunization" ("id");

ALTER TABLE "ImmunizationRecord" ADD FOREIGN KEY ("vaccineTypeId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "MedicalCondition" ADD FOREIGN KEY ("medicalHistoryId") REFERENCES "MedicalHistory" ("id");

ALTER TABLE "MedicalCondition" ADD FOREIGN KEY ("conditionId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "HospitalizationRecord" ADD FOREIGN KEY ("hospitalizationId") REFERENCES "Hospitalization" ("id");

ALTER TABLE "OperationRecord" ADD FOREIGN KEY ("operationId") REFERENCES "Operation" ("id");

ALTER TABLE "OperationRecord" ADD FOREIGN KEY ("procedureId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "DentalProcedureRecord" ADD FOREIGN KEY ("dentalProcedureId") REFERENCES "DentalProcedure" ("id");

ALTER TABLE "DentalProcedureRecord" ADD FOREIGN KEY ("procedureTypeId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "ComplaintTagLinks" ADD FOREIGN KEY ("complaintId") REFERENCES "ConsultationComplaints" ("id");

ALTER TABLE "ComplaintTagLinks" ADD FOREIGN KEY ("tagId") REFERENCES "ComplaintTags" ("id");

ALTER TABLE "ComplaintDiagnosisLink" ADD FOREIGN KEY ("complaintId") REFERENCES "ConsultationComplaints" ("id");

ALTER TABLE "ComplaintDiagnosisLink" ADD FOREIGN KEY ("diagnosisId") REFERENCES "ConsultationDiagnosis" ("id");

ALTER TABLE "DiagnosisTreatmentLink" ADD FOREIGN KEY ("diagnosisId") REFERENCES "ConsultationDiagnosis" ("id");

ALTER TABLE "DiagnosisTreatmentLink" ADD FOREIGN KEY ("treatmentId") REFERENCES "ConsultationTreatment" ("id");

ALTER TABLE "DiagnosisPEFindingsLink" ADD FOREIGN KEY ("findingId") REFERENCES "ConsultationPEFindings" ("id");

ALTER TABLE "DiagnosisPEFindingsLink" ADD FOREIGN KEY ("diagnosisId") REFERENCES "ConsultationDiagnosis" ("id");

ALTER TABLE "patientUpdateLog" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "OralApplianceRecord" ADD FOREIGN KEY ("applianceId") REFERENCES "OralAppliance" ("id");

ALTER TABLE "OralApplianceRecord" ADD FOREIGN KEY ("tagId") REFERENCES "oralApplianceCatalog" ("id");

ALTER TABLE "ConsultationVirtual" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "ConsultationVirtualPrompt" ADD FOREIGN KEY ("consultationVirtualId") REFERENCES "ConsultationVirtual" ("id");

ALTER TABLE "ConsultationDiagnosis" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "ConsultationPEFindings" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "ConsultationTreatment" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "ConsultationComplaints" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "Consultation" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "patientSlot" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "oralFindingRecord" ADD FOREIGN KEY ("oralFindingId") REFERENCES "oralFindingCatalog" ("id");

ALTER TABLE "oralFindingRecord" ADD FOREIGN KEY ("dentalRecordId") REFERENCES "DentalRecord" ("id");

ALTER TABLE "ToothPlacement" ADD FOREIGN KEY ("dentalRecordId") REFERENCES "DentalRecord" ("id");

ALTER TABLE "documentRequirements" ADD FOREIGN KEY ("templateId") REFERENCES "documentTemplate" ("id");

ALTER TABLE "documentRequirements" ADD FOREIGN KEY ("requirementtagId") REFERENCES "documentRequirementsTag" ("id");

ALTER TABLE "documentData" ADD FOREIGN KEY ("requirementId") REFERENCES "documentRequirements" ("id");

ALTER TABLE "PatientDocuments" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "ConsultationOutcome" ADD FOREIGN KEY ("consultationId") REFERENCES "Consultation" ("id");

ALTER TABLE "schedulerWhitelist" ADD FOREIGN KEY ("slotSchedulerId") REFERENCES "slotScheduler" ("id");

ALTER TABLE "schedulerWhitelist" ADD FOREIGN KEY ("patientId") REFERENCES "Patients" ("id");

ALTER TABLE "rolesMap" ADD FOREIGN KEY ("personnelId") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "rolesMap" ADD FOREIGN KEY ("rolesId") REFERENCES "RolesTable" ("id");

ALTER TABLE "rolesMap" ADD FOREIGN KEY ("assignedBy") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "PatientDocuments" ADD FOREIGN KEY ("templateId") REFERENCES "documentTemplate" ("id");

ALTER TABLE "documentData" ADD FOREIGN KEY ("documentId") REFERENCES "PatientDocuments" ("id");

ALTER TABLE "ConsultationTreatment" ADD FOREIGN KEY ("issued_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "ConsultationVirtualPrompt" ADD FOREIGN KEY ("userId") REFERENCES "UserCredentials" ("id");

ALTER TABLE "ConsultationOutcome" ADD FOREIGN KEY ("recordedBy") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "ConsultationDiagnosis" ADD FOREIGN KEY ("diagnosed_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "patientUpdateLog" ADD FOREIGN KEY ("approved_by") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "UsersPersonalLog" ADD FOREIGN KEY ("approvedBy") REFERENCES "MedicalPersonnel" ("id");

ALTER TABLE "EmergencyContact" ADD FOREIGN KEY ("firstNumber") REFERENCES "EmergencyNumber" ("id");

ALTER TABLE "EmergencyContact" ADD FOREIGN KEY ("secondNumber") REFERENCES "EmergencyNumber" ("id");

ALTER TABLE "MedicationRecord" ADD FOREIGN KEY ("medicationId") REFERENCES "MaintenanceMedication" ("id");

ALTER TABLE "AllergyRecord" ADD FOREIGN KEY ("allergyId") REFERENCES "Allergy" ("id");

ALTER TABLE "AllergyRecord" ADD FOREIGN KEY ("allergenCatalogId") REFERENCES "AllergenCatalog" ("id");

ALTER TABLE "scheduleRequirement" ADD FOREIGN KEY ("slotId") REFERENCES "slotScheduler" ("id");

ALTER TABLE "patientSlot" ADD FOREIGN KEY ("slotEntityId") REFERENCES "ScheduleDateEntity" ("id");

ALTER TABLE "HospitalizationRecord" ADD FOREIGN KEY ("conditionId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "MedicationRecord" ADD FOREIGN KEY ("medicineId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "profileRecord" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "VisualAcuityRecord" ADD FOREIGN KEY ("acuityId") REFERENCES "DomainTypeCatalog" ("id");

ALTER TABLE "VisualAcuityRecord" ADD FOREIGN KEY ("id") REFERENCES "VisualAcuity" ("id");

ALTER TABLE "ObGynHistory" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Lifestyle" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "DentalRecord" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "DentalPhotoRecord" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "VisualAcuity" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "MedicalHistory" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Hospitalization" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Operation" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Immunization" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "DentalProcedure" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "MaintenanceMedication" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Allergy" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "EmergencyContact" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "OralAppliance" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "VitalSigns" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "DentalHistory" ADD FOREIGN KEY ("id") REFERENCES "patientUpdateLog" ("id");

ALTER TABLE "Patients" ADD FOREIGN KEY ("id") REFERENCES "UserCredentials" ("id");

ALTER TABLE "MedicalPersonnel" ADD FOREIGN KEY ("id") REFERENCES "UserCredentials" ("id");

ALTER TABLE "UsersPersonal" ADD FOREIGN KEY ("id") REFERENCES "UserCredentials" ("id");

ALTER TABLE "DomainTypeCatalog" ADD FOREIGN KEY ("created_by") REFERENCES "UserCredentials" ("id");

ALTER TABLE "oralFindingCatalog" ADD FOREIGN KEY ("created_by") REFERENCES "UserCredentials" ("id");

ALTER TABLE "AllergenCatalog" ADD FOREIGN KEY ("created_by") REFERENCES "UserCredentials" ("id");