scalar Date
scalar UUID

enum LOCATION_DESIGNATION {
  Arlegui
  Casal
  QuezonCity
}

enum SCHEDULING_STATUS {
  Pending
  Scheduled
  InProgress
  Rejected
  Expired
  Completed
  NoShow
  CancelledByPatient
  CancelledByMedical
}

enum SCHEDULE_SESSION {
  Morning
  Afternoon
}


enum PATIENT_TYPE {
  Student
  Employee
}

type SlotScheduler {
  id: ID!
  label: String!
  location: LOCATION_DESIGNATION!
  patientType: PATIENT_TYPE
  schedulePerWeek: [String!]!
  morningAllowed: Int!
  afternoonAllowed: Int!
  notes: String
  purposeRequired: Boolean
  isActive: Boolean!
  containsCustomDates: Boolean!
  whitelistOnly: Boolean
  created_at: Date
}

type SlotCustomDateEntry {
  id: ID!
  slotScheduleId: ID!
  scheduledDate: Date!
  morningAllowed: Int
  afternoonAllowed: Int
  created_at: Date
}

input SlotCustomDateInput {
  scheduledDate: Date!
  morningAllowed: Int
  afternoonAllowed: Int
}

input SlotSchedulerInput {
  label: String!
  location: LOCATION_DESIGNATION!
  patientType: PATIENT_TYPE
  schedulePerWeek: [String!]!
  morningAllowed: Int!
  afternoonAllowed: Int!
  notes: String
  purposeRequired: Boolean
  slotCustomDates: [Date!]!
  whiteLists: [ID!]!
  whitelistOnly: Boolean!
}

input SlotSchedulerUpdateInput {
  label: String
  location: LOCATION_DESIGNATION
  patientType: PATIENT_TYPE
  schedulePerWeek: [String!]
  morningAllowed: Int
  afternoonAllowed: Int
  notes: String
  purposeRequired: Boolean
  isActive: Boolean
  whitelistOnly: Boolean
}



type ScheduleWhitelist {
  id: ID!
  slotSchedulerId: ID!
  patientId: ID!
}

type WhitelistEntry {
  id: ID!
  slotSchedulerId: ID!
  patientId: ID!
  patientIdentifier: Int
  patientName: String
}

input ScheduleWhitelistInput {
  slotSchedulerId: ID!
  patientId: ID!
}




type ScheduleDateEntity{
  id: ID!
  slotId: ID!
  morningAllowed: Int!
  morningRegistered: Int!
  morningPending: Int!
  afternoonAllowed: Int!
  afternoonRegistered: Int!
  afternoonPending: Int!
  allowDuring: Boolean!
  scheduledDate: Date!
}

input ScheduleDateEntityUpdate {
  morningAllowed: Int
  afternoonAllowed: Int
  allowDuring: Boolean
  scheduledDate: Date
}

type ScheduleRequirement {
  id: ID!
  slotId: ID!
  label: String!
  notes: String
  isDigital: Boolean!
  isActive: Boolean!
}

input ScheduleRequirementInput {
  label: String!
  notes: String
  isDigital: Boolean
  isActive: Boolean
}

type patientScheduleRequirement {
  id: ID!
  scheduleRequirementId: ID!
  filename: UUID!
  created_at: Date!
}

input patientScheduleRequirementInput {
  scheduleRequirementId: ID!
  filename: UUID!
}

type patientSlot {
  id: ID!
  patientId: ID!
  patientIdentifier: Int
  patientName: String
  patientEmail: String
  slotEntityId: ID!
  status: SCHEDULING_STATUS!
  session: SCHEDULE_SESSION!
  scheduledDate: Date
  schedulerLabel: String
  requirements: [patientScheduleRequirement!]!
  approvedBy: String
  purpose: String
  notes: String
  arrived_at: Date
  created_at: Date!
}

type StatusCount {
  status: SCHEDULING_STATUS!
  count: Int!
}

input patientSlotInput { # for medical only
  slotEntityId: ID!
  status: SCHEDULING_STATUS!
  session: SCHEDULE_SESSION!
  notes: String
}

# Queries
type Query {
  listOpenAppointments(offset: Int, limit: Int): [SlotScheduler!] # list all open appointments
  listCustomDates(schedulerId: ID!, offset: Int, limit: Int): [SlotCustomDateEntry!]
  listAppointmentSchedule(schedulerId: ID!, date: Date!): ScheduleDateEntity 
  listAppointmentRequirements(schedulerId: ID!, offset: Int, limit: Int): [ScheduleRequirement!]

  getAppointmentStatus: patientSlot
  #----------- --^ Patient and --v Medical
  getUserAppointmentStatus(userId: ID!): SCHEDULING_STATUS

  getUserAppointmentRecords(userId: ID!, offset: Int, limit: Int): [patientSlot!]

  listAllOpenAppointments(location: LOCATION_DESIGNATION, offset: Int, limit: Int): [SlotScheduler!]
  listAllAppointmentRequirements(schedulerId: ID!, offset: Int, limit: Int): [ScheduleRequirement!]
  listMonthAvailability(schedulerId: ID!, startDate: Date!, endDate: Date!): [ScheduleDateEntity!]

  searchAppointmentStatuses(status: SCHEDULING_STATUS!, location: LOCATION_DESIGNATION, date: Date, schedulerId: ID, offset: Int, limit: Int): [patientSlot!]
  getAppointmentStatusCounts(location: LOCATION_DESIGNATION, schedulerId: ID, date: Date): [StatusCount!]
  listSchedulerWhitelist(schedulerId: ID!, offset: Int, limit: Int): [WhitelistEntry!]
}

# Mutations
type Mutation {
  submitAppointment(schedulerId: ID!, date: Date!, session: SCHEDULE_SESSION!, requirements: [patientScheduleRequirementInput!]!, purpose: String): patientSlot
  cancelAppointment: Boolean

  #----------- --^ Patient and --v Medical
  respondAppointment(userId: ID!, slotId: ID, status: SCHEDULING_STATUS!, notes: String): patientSlot
  recordAppointmentAttendance(slotId: ID!, arrived_at: Date!): patientSlot

  createScheduler(input: SlotSchedulerInput!): SlotScheduler
  updateScheduler(schedulerId: ID!, input: SlotSchedulerUpdateInput!): SlotScheduler
  deleteScheduler(schedulerId: ID!): Boolean

  updateSchedulerRequirement(schedulerId: ID!, input: ScheduleRequirementInput!): ScheduleRequirement
  deleteSchedulerRequirement(schedulerId: ID!, label: String!): Boolean

  setCustomDates(schedulerId: ID!, dates: [SlotCustomDateInput!]!): [SlotCustomDateEntry!]
  unsetCustomDates(schedulerId: ID!, dates: [Date!]!): [Date!]

  addEntryWhitelist(schedulerId: ID!, patientIds: [ID!]!): [ID!]
  removeEntryWhitelist(schedulerId: ID!, patientIds: [ID!]!): [ID!]

  updateDateIdentity(schedulerId: ID!, date: Date!, input: ScheduleDateEntityUpdate!): ScheduleDateEntity
}
