const mockDoc = { y: 100, page: { width: 612, height: 792, margins: { bottom: 72 } }, moveDown: jest.fn(), addPage: jest.fn(), fontSize: jest.fn().mockReturnThis(), font: jest.fn().mockReturnThis(), fillColor: jest.fn().mockReturnThis(), text: jest.fn().mockReturnThis() };
jest.mock('../../rendering/pdfkit', () => ({ DEFAULT_MARGINS: {}, FONT_SIZES: { body: 10, small: 8 }, COLORS: { text: '#111', secondary: '#555' }, createDocument: jest.fn(() => mockDoc), addHeader: jest.fn(), addSectionHeading: jest.fn(), addField: jest.fn(), addTable: jest.fn(), embedImage: jest.fn(), addSignatureLine: jest.fn() }));
jest.mock('../../rendering/chart', () => ({ generatePieChart: jest.fn().mockResolvedValue(Buffer.from('chart')), generateLineChart: jest.fn().mockResolvedValue(Buffer.from('chart')), generateBarChart: jest.fn().mockResolvedValue(Buffer.from('chart')), generateDoughnutChart: jest.fn().mockResolvedValue(Buffer.from('chart')) }));

const pdf = require('../../rendering/pdfkit');
const chart = require('../../rendering/chart');
const StaffReport = require('./staff-report');

beforeEach(() => { jest.clearAllMocks(); mockDoc.y = 100; });

test('renders report metadata, summary, chart sections, and generated signature', async () => {
  const template = new StaffReport().setData({ report: { title: 'Quarterly', subtitle: 'Q1', branch: 'Manila', dateRange: { startDate: '2026-01-01', endDate: '2026-03-31' }, generatedAt: '2026-04-01' }, summary: { totalPatients: 120, customValue: 3 }, sections: [{ title: 'By Type', chartType: 'pie', labels: ['Medical'], values: [4], total: 4, summary: 'Four' }], physician: { firstName: 'A', lastName: 'B' } });
  await expect(template.build()).resolves.toBe(template);
  expect([StaffReport.type, StaffReport.displayName, StaffReport.persistToDatabase]).toEqual(['staff-report', 'Staff Analytics Report', false]);
  expect(pdf.addHeader).toHaveBeenCalledWith(mockDoc, 'Quarterly', 'Q1', expect.any(Object));
  expect(pdf.addTable).toHaveBeenCalled();
  expect(chart.generatePieChart).toHaveBeenCalled();
  expect(pdf.embedImage).toHaveBeenCalled();
  expect(mockDoc.text).toHaveBeenCalledWith('Generated by: A B', expect.any(Object));
});

test('handles empty report blocks and chart render failures', async () => {
  chart.generateBarChart.mockRejectedValueOnce(new Error('render error'));
  const template = new StaffReport().setData({ report: null, summary: null, sections: [{ title: 'Failed chart', chartType: 'bar', labels: ['A'], values: [1] }], physician: null });
  await template.build();
  expect(mockDoc.text).toHaveBeenCalledWith('[Chart could not be generated]');
});

test('renders metadata defaults, all summary values, box plots, blood pressure, trends, and chart variants', async () => {
  const template = new StaffReport().setData({ report: {}, summary: { totalPatients: 1, newPatients: 2, totalConsultations: 3, appointmentsCompleted: 4, medicineIssued: 5, customNumber: 6, customText: 'seven' }, sections: [
    { title: 'Box', isBoxPlot: true, boxPlot: [{ name: 'BMI', min: null, q1: null, median: null, q3: null, max: null, count: null }], labels: ['BMI'], values: [2], chartType: 'doughnut' },
    { title: 'Pressure', isBP: true, labels: ['Jan'], values: [120], diastolicValues: [80], chartType: 'pie' },
    { title: 'Trend', isTrend: true, labels: ['Jan'], values: [0], chartType: 'line' },
    { title: 'Percent', labels: ['A'], values: [2], total: 4, chartType: 'unknown', summary: 'sum' },
    { title: 'No pct', labels: ['A'], values: [0], total: 0, showPercentage: false, chartType: 'bar' },
    { title: 'Zero total', labels: ['A'], values: [0], total: 0, chartType: 'bar' },
    { title: 'Zero BP', isBP: true, labels: ['Feb'], values: [0], diastolicValues: [0], chartType: 'bar' },
    { title: 'No labels', labels: [], values: [], chartType: 'doughnut' },
  ], physician: { firstName: 'A', lastName: 'B' } });
  template.init();
  template._addReportMetadata();
  template._addSummaryStats();
  await template._addChartSections();
  template._addGeneratorSignature();
  expect(pdf.addField).toHaveBeenCalledWith(mockDoc, 'Branch', 'All Branches');
  expect(pdf.addTable).toHaveBeenCalledWith(mockDoc, ['#', 'Vital', 'Min', 'Q1', 'Median', 'Q3', 'Max', 'n'], expect.any(Array), expect.any(Object));
  expect(chart.generateLineChart).toHaveBeenCalledWith(['Jan'], expect.any(Array), expect.any(Object));
  expect(chart.generateDoughnutChart).toHaveBeenCalled();
  expect(chart.generateBarChart).toHaveBeenCalled();
  expect(mockDoc.text).toHaveBeenCalledWith('Generated by: A B', expect.any(Object));
});

test('skips optional blocks, handles page breaks, and generates filenames with branch/date fallback', async () => {
  const template = new StaffReport().setData({ report: null, summary: {}, sections: [], physician: null });
  template.init();
  template.data.physician = null;
  expect(template._getDateRangeLabel()).toBe('');
  template._addReportMetadata(); template._addSummaryStats(); template._addGeneratorSignature();
  await template._addChartSections();
  expect(template.generateFilename()).toContain('staff_report_all_');
  template.data.sections = [{ title: 'Tall', labels: [], values: [], chartType: 'bar' }];
  mockDoc.y = 600;
  await template._addChartSections();
  expect(mockDoc.addPage).toHaveBeenCalled();
});
