scalar Date

enum ItemCategory {
  Medicine
  Supply
}

enum DosageUnit {
  mg
  g
  mcg
  ml
  L
  IU
}

enum SupplyUnit {
  pcs
  box
  pack
  set
  kit
}

enum LocationDesignation {
  Arlegui
  Casal
  QuezonCity
}

type MedicalItem {
  id: ID!
  item_code: String
  item_name: String
  category: ItemCategory
  description: String
  active: Boolean
  created_at: Date
  updated_at: Date
}

type MedicineBatch {
  id: ID!
  medicalItemId: Int!
  supplierName: String
  batchNumber: String
  dosageUnit: DosageUnit
  dosageValue: Int
  availableQuantity: Int
  expiryDate: Date
  location: LocationDesignation
  receivedBy: Int
  notes: String
  created_at: Date
  updated_at: Date
}

type SupplyBatch {
  id: ID!
  supplyItemId: Int!
  batchNumber: String
  unit: SupplyUnit
  currentQuantity: Int
  expiryDate: Date
  location: LocationDesignation
  receivedBy: Int
  supplierName: String
  notes: String
  created_at: Date
  updated_at: Date
}

input MedicalItemInput {
  item_code: String!
  item_name: String!
  category: ItemCategory!
  description: String
}

input MedicalItemUpdateInput {
  item_code: String
  item_name: String
  category: ItemCategory
  description: String
  active: Boolean
}

input MedicineBatchInput {
  medicalItemId: Int!
  supplierName: String
  batchNumber: String!
  dosageUnit: DosageUnit!
  dosageValue: Int!
  expiryDate: Date!
  location: LocationDesignation!
  quantity: Int!
  notes: String
}

input SupplyBatchInput {
  supplyItemId: Int!
  batchNumber: String!
  initialQuantity: Int!
  unit: SupplyUnit!
  expiryDate: Date
  location: LocationDesignation!
  supplierName: String
  notes: String
}

input MedicalSupplyUpdateInput {
  expiryDate: Date
  notes: String
}

input SplitMedicalSupplyInput {
  quantity: Int!
  targetLocation: LocationDesignation!
  notes: String
}

type Query {
  getMedicalItems(category: ItemCategory, active: Boolean, offset: Int, limit: Int): [MedicalItem!]
  getMedicalItem(id: ID!): MedicalItem
  getMedicalSupply(medicalItemId: Int!, location: LocationDesignation, availableOnly: Boolean, offset: Int, limit: Int): [MedicineBatch!]
  getSupplyBatches(supplyItemId: Int!, location: LocationDesignation, availableOnly: Boolean, offset: Int, limit: Int): [SupplyBatch!]
}

type Mutation {
  createMedicalItems(input: MedicalItemInput!): MedicalItem
  updateMedicalItems(id: ID!, input: MedicalItemUpdateInput!): MedicalItem
  deleteMedicalItems(id: ID!): Boolean

  addMedicalSupply(input: MedicineBatchInput!): MedicineBatch
  addSupplyBatch(input: SupplyBatchInput!): SupplyBatch

  splitMedicalSupply(batchId: ID!, input: SplitMedicalSupplyInput!): SupplyBatch
  splitMedicineSupply(batchId: ID!, input: SplitMedicalSupplyInput!): MedicineBatch
  updateMedicalSupply(batchId: ID!, input: MedicalSupplyUpdateInput!): MedicineBatch
  updateSupplyBatch(batchId: ID!, input: MedicalSupplyUpdateInput!): SupplyBatch
}